### PR TITLE
Added bad word check like the Perl module

### PR DESCRIPTION
**Pull request by PhilHannent**
I've added a small check for the rude words and all tests pass.

Also I updated the dependencies just for completeness.

### CODE REVIEW

**Comment by chilts** [comment]
Awesome. This is nice.

Two things though. (1) travis failed related to the version of inflight (perhaps something to do with bumping the packages), and (2) is it worth doing a test for an actual bad word appearing? Thanks.

**Comment by chilts** [comment]
Ok, I've removed the v0.8 from the `.travis.yml` file and changed v0.11 to v0.12. That was ancient. If you rebase onto master and perhaps add a test, then I'll merge. Cheers.

**Comment by PhilHannent** [comment]
Afternoon,

I've rebased on your upstream and added a set of tests for the rude words.

**Comment by chilts** [comment]
Awesome work @PhilHannent. :) Released as v0.4.0. Many thanks.

**Pull request merged**
